### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by exile85** [Davi5Alexander/docker_pppwn#3]
Have a problem with FWV 11.00
docker says file not found.
i allready changed the stages to ...1100.bin and also used your newly uploaded stages, but same problem:
![grafik](https://github.com/Davi5Alexander/docker_pppwn/assets/102905134/81c0372b-418e-49a9-835d-a7a280953acc)

With version 900 no problem but my ps4 has version 11.00

**Comment by PhR34x0r** [comment]
it should work when you set the version to "11.00" instead of "1100"

**Comment by exile85** [comment]
Where in the config or the bin File?
I'm wondering why Alexander reuped the bin Files with 1100 instead of 11.00
Also the config can't handle 11.00, i tried it allready
