### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by shoyrock** [Davi5Alexander/docker_pppwn#4]
Hey, I just wanted to know if it can be used on a NAS that is on the same network as the PS4 or if just it has to be plugged into the PS4 directly

**Comment by Davi5Alexander** [comment]
This runs PPPwn on a network interface over eterneth. It does not run on a specific device. But you can use a USB device with ethernet to use it exclusively for the PS4.This way you would have two Ethernet network interfaces, one for the PS4 and another to use your NAS normally.
